# Generated by Django 5.1.6 on 2025-02-25 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('parent_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم هاتف ولي الأمر')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('grade', models.CharField(choices=[('1', 'الصف الدراسي الأول'), ('2', 'الصف الدراسي الثاني'), ('3', 'الصف الدراسي الثالث')], max_length=50, verbose_name='الصف الدراسي')),
                ('password', models.CharField(default='default_password', max_length=128, verbose_name='كلمة المرور')),
                ('videos_watched', models.PositiveIntegerField(default=0, verbose_name='عدد الفيديوهات المشاهدة')),
                ('exams_completed', models.PositiveIntegerField(default=0, verbose_name='عدد الاختبارات المنهية')),
                ('average_score', models.FloatField(default=0.0, verbose_name='متوسط النتائج')),
                ('total_lecture_time', models.PositiveIntegerField(default=0, verbose_name='إجمالي مدة المحاضرات (بالدقائق)')),
                ('total_video_views', models.PositiveIntegerField(default=0, verbose_name='إجمالي عدد مرات مشاهدة الفيديوهات')),
                ('total_exam_views', models.PositiveIntegerField(default=0, verbose_name='إجمالي عدد مرات فتح الاختبارات')),
                ('total_exam_completions', models.PositiveIntegerField(default=0, verbose_name='إجمالي عدد مرات إنهاء الاختبارات')),
                ('attempted_exams', models.ManyToManyField(blank=True, related_name='students_who_attempted', to='content.exam', verbose_name='الامتحانات المجربة')),
                ('courses', models.ManyToManyField(blank=True, related_name='student_courses', to='content.course', verbose_name='الكورسات')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed_lectures', models.ManyToManyField(blank=True, related_name='students_who_watched', to='content.lecture', verbose_name='المحاضرات المشاهدة')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025, editable=False, verbose_name='السنة')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='content.course', verbose_name='الكورسات')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.student', verbose_name='الطالب')),
            ],
        ),
    ]
