# Generated by Django 5.1.6 on 2025-06-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course_enrollment_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='_phash',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
