# Generated by Django 5.1.6 on 2025-06-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_paymentrequest_recipient_phone_and_more'),
        ('content', '0006_remove_lecture_youtube_link_lecture_youtube_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
