# Generated by Django 5.1.6 on 2025-07-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_enrollment_course_alter_paymentrequest_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='student',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
