# Generated by Django 5.1.6 on 2025-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_enrollment_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
