# Generated by Django 5.1.6 on 2025-07-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_student_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='student',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
