# Generated by Django 5.1.6 on 2025-07-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_paymentrequest_course_and_more'),
        ('content', '0013_lecture_attendance_delete_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='student',
        ),
        migrations.AddField(
            model_name='subscription',
            name='students',
            field=models.ManyToManyField(related_name='subscriptions', to='accounts.student', verbose_name='الطلاب'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='subscribed_students', to='content.course', verbose_name='الكورسات'),
        ),
    ]
