# Generated by Django 5.1.6 on 2025-07-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_subscription_student_subscription_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_subscriptions', to='accounts.student', verbose_name='طالب مفرد'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='bulk_subscriptions', to='accounts.student', verbose_name='طلاب جماعي'),
        ),
    ]
