# Generated by Django 5.1.6 on 2025-07-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subscription_student_alter_subscription_students'),
        ('content', '0013_lecture_attendance_delete_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='students',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='content.course', verbose_name='الكورسات'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.student', verbose_name='الطالب'),
        ),
    ]
