# Generated by Django 5.1.6 on 2025-07-22 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_subscription_students_and_more'),
        ('content', '0014_remove_lecture_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='exams_completed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='videos_watched',
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='content.course', verbose_name='الكورسات'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='content.course', verbose_name='الكورسات'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.student'),
        ),
    ]
