# Generated by Django 5.1.6 on 2025-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='default_password', max_length=128, verbose_name='كلمة المرور'),
        ),
    ]
