# Generated by Django 5.1.6 on 2025-07-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_student_password'),
        ('content', '0015_alter_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exams_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الاختبارات المنهية'),
        ),
        migrations.AddField(
            model_name='student',
            name='videos_watched',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الفيديوهات المشاهدة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='student_courses', to='content.course', verbose_name='الكورسات'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='content.course', verbose_name='الكورسات'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.student', verbose_name='الطالب'),
            preserve_default=False,
        ),
    ]
