# Generated by Django 5.1.6 on 2025-07-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_student_exams_completed_student_videos_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='target_grade',
            field=models.CharField(blank=True, choices=[('1', 'الصف الدراسي الأول الثانوي'), ('2', 'الصف الدراسي الثاني الثانوي'), ('3', 'الصف الدراسي الثالث الثانوي')], help_text='إذا ضبطت هذا الحقل، سيطبق الاشتراك على جميع طلبة هذا الصف الدراسي', max_length=1, null=True, verbose_name='صف دراسي مستهدف'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.student', verbose_name='الطالب'),
        ),
    ]
