# Generated by Django 5.1.6 on 2025-08-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_subscription_target_grade_alter_subscription_student'),
        ('content', '0017_alter_examattendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lecture_view', 'فتح صفحة المحاضرة'), ('lecture_progress', 'تقدّم مشاهدة المحاضرة'), ('lecture_present', 'اكتمل مشاهدة المحاضرة (حاضر)'), ('exam_started', 'بدء امتحان'), ('exam_submitted', 'تم إرسال إجابات الامتحان'), ('exam_completed', 'اكتمل الامتحان'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('other', 'نشاط آخر')], max_length=30, verbose_name='نوع النشاط')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='تفاصيل')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='الدرجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.exam', verbose_name='الامتحان')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.lecture', verbose_name='المحاضرة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ('-created_at',),
            },
        ),
    ]
