# Generated by Django 5.1.6 on 2025-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الدراسي الأول'), ('2', 'الصف الدراسي الثاني'), ('3', 'الصف الدراسي الثالث'), ('4', 'أولى إعدادي'), ('5', 'تانية إعدادي'), ('6', 'تالته إعدادي')], max_length=50, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='target_grade',
            field=models.CharField(blank=True, choices=[('1', 'الصف الدراسي الأول الثانوي'), ('2', 'الصف الدراسي الثاني الثانوي'), ('3', 'الصف الدراسي الثالث الثانوي'), ('4', 'أولى إعدادي'), ('5', 'تانية إعدادي'), ('6', 'تالته إعدادي')], help_text='إذا ضبطت هذا الحقل، سيطبق الاشتراك على جميع طلبة هذا الصف الدراسي', max_length=1, null=True, verbose_name='صف دراسي مستهدف'),
        ),
    ]
