# Generated by Django 5.1.6 on 2026-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_student_grade_alter_subscription_target_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي'), ('4', 'أولى إعدادي'), ('5', 'تانية إعدادي'), ('6', 'تالته إعدادي')], max_length=50, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='رقم هاتف ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='year',
            field=models.PositiveIntegerField(default=2026, editable=False, verbose_name='السنة'),
        ),
    ]
