# Generated by Django 5.1.6 on 2026-07-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_student_grade_and_more'),
        ('accounts', '0020_consolidate_name_and_phone'),
    ]

    operations = [
    ]
