# Generated by Django 5.1.6 on 2026-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20260725_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='رقم هاتف ولي الأمر'),
        ),
    ]
