# Generated by Django 5.1.6 on 2025-03-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_lecture_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط فيديو YouTube'),
        ),
    ]
