# Generated by Django 5.1.6 on 2025-07-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_examprogress_lectureprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='مدة المحاضرة (بالدقائق)'),
        ),
    ]
