# Generated by Django 5.1.6 on 2025-07-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_enrollment_paymentrequest'),
        ('content', '0008_lecture_duration_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_attempted_students',
            field=models.ManyToManyField(blank=True, related_name='content_exam_attempted', to='accounts.student', verbose_name='الطلاب الحاضرون'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_watched_students',
            field=models.ManyToManyField(blank=True, related_name='content_lecture_watched', to='accounts.student', verbose_name='الطلاب الحاضرون'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ آخر تحديث'),
        ),
    ]
