# Generated by Django 5.1.6 on 2025-07-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_course_options_exam_exam_attempted_students_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lectureprogress',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='lectureprogress',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_attempted_students',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_watched_students',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='مدة المحاضرة (بالدقائق)'),
        ),
        migrations.DeleteModel(
            name='ExamProgress',
        ),
        migrations.DeleteModel(
            name='LectureProgress',
        ),
    ]
