# Generated by Django 5.1.6 on 2025-07-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_lectureprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='مدة المحاضرة (بالثواني)'),
        ),
    ]
