# Generated by Django 5.1.6 on 2025-07-14 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_lecture_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('absent', 'غياب'), ('present', 'حضور')], default='absent', max_length=7, verbose_name='الحالة')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='content.lecture', verbose_name='المحاضرة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل حضور/غياب',
                'verbose_name_plural': 'سجلات الحضور والغياب',
                'unique_together': {('student', 'lecture')},
            },
        ),
    ]
