# Generated by Django 5.1.6 on 2025-07-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='attendance',
            field=models.JSONField(default=dict, help_text="مثال: {'absent': [1,2,3], 'present': []}", verbose_name='سجل الحضور/الغياب'),
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
