# Generated by Django 5.1.6 on 2025-07-22 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_lecture_attendance_delete_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='duration_seconds',
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='تاريخ آخر تحديث'),
            preserve_default=False,
        ),
    ]
