# Generated by Django 5.1.6 on 2025-07-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_subscription_target_grade_alter_subscription_student'),
        ('content', '0015_alter_course_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.course', verbose_name='الكورس'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='مدة الامتحان (دقائق)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_mcq_score',
            field=models.PositiveIntegerField(default=0, verbose_name='المجموع الكلي للاختيارات'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.course', verbose_name='الكورس'),
        ),
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('absent', 'غائب'), ('present', 'حاضر')], max_length=7, verbose_name='الحالة')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='content.exam', verbose_name='الامتحان')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendances', to='accounts.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حضور امتحان',
                'verbose_name_plural': 'سجلات حضور الامتحانات',
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('absent', 'غائب'), ('present', 'حاضر')], max_length=7, verbose_name='الحالة')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='content.lecture', verbose_name='المحاضرة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to='accounts.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حضور محاضرة',
                'verbose_name_plural': 'سجلات حضور المحاضرات',
                'unique_together': {('student', 'lecture')},
            },
        ),
    ]
