# Generated by Django 5.1.6 on 2025-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_course_updated_at_alter_exam_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='lecture_pdfs/', verbose_name='ملف PDF للمحاضرة'),
        ),
    ]
