# Generated by Django 5.1.6 on 2025-08-08 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_subscription_target_grade_alter_subscription_student'),
        ('content', '0016_alter_course_updated_at_alter_exam_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examattendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lectureattendance',
            options={},
        ),
        migrations.AddField(
            model_name='examattendance',
            name='answered_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المجيبة'),
        ),
        migrations.AddField(
            model_name='examattendance',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي عدد الأسئلة'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='مدة المحاضرة بالثواني'),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='lecture_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='مدة المحاضرة بالثواني'),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='ثواني مشاهدة'),
        ),
        migrations.AlterField(
            model_name='examattendance',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='content.exam'),
        ),
        migrations.AlterField(
            model_name='examattendance',
            name='status',
            field=models.CharField(choices=[('absent', 'غائب'), ('present', 'حاضر')], default='absent', max_length=7),
        ),
        migrations.AlterField(
            model_name='examattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendances', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='examattendance',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='content.lecture'),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='status',
            field=models.CharField(choices=[('absent', 'غائب'), ('present', 'حاضر')], default='absent', max_length=7),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
