# Generated by Django 5.1.6 on 2025-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_examattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي'), ('4', 'أولى إعدادي'), ('5', 'تانية إعدادي'), ('6', 'تالته إعدادي')], default='1', max_length=10, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي'), ('4', 'أولى إعدادي'), ('5', 'تانية إعدادي'), ('6', 'تالته إعدادي')], max_length=10, null=True, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي'), ('4', 'أولى إعدادي'), ('5', 'تانية إعدادي'), ('6', 'تالته إعدادي')], max_length=10, null=True, verbose_name='الصف الدراسي'),
        ),
    ]
