# Generated by Django 5.1.6 on 2026-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_course_grade_alter_exam_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(verbose_name='النص')),
                ('number', models.IntegerField(verbose_name='الرقم')),
                ('image', models.ImageField(upload_to='top_students/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Top student',
                'verbose_name_plural': 'Top students',
            },
        ),
    ]
